server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: true
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
        - src/main/java/
  thymeleaf:
    cache: false
    enabled: true
    prefix: file:src/main/resources/templates/
    suffix: .html
